services:
  postgres:
    image: postgres:16.4-alpine
    restart: unless-stopped
    ports:
      - "54321:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    command: "postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF"

volumes:
  postgres: